src/Metaflo/SchemoBundle/Entity/Room.php
<?php

namespace Metaflo\SchemoBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;
use JMS\Serializer\Annotation\MaxDepth;

/**
 * Room
 *
 * @ORM\Table()
 * @ORM\Entity
 * @ExclusionPolicy("all")
 */
class Room {
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\Column(name="usageType", type="smallint")
     */
    private $usageType;

    const USAGE_CLASS = 0;
    const USAGE_ACTIVITY = 1;
    public static $usages
        = array(
            self::USAGE_CLASS => "class",
            self::USAGE_ACTIVITY => "activity"
        );

    /**
     * @var string
     *
     * @ORM\Column(name="usageName", type="string", length=255)
     */
    private $usageName;

    /**
     * @var string
     *
     * @Expose
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var LessonTemplate[]
     *
     * @ORM\OneToMany(targetEntity="LessonTemplate", mappedBy="roomTypical")
     */
    private $lessonTemplates;

    /**
     * @var Lesson[]
     *
     * @ORM\OneToMany(targetEntity="Lesson", mappedBy="room")
     */
    private $lessonsAssigned;

    /**
     * @var Project
     *
     * @ORM\ManyToOne(targetEntity="Project", inversedBy="rooms")
     */
    private $project;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set usageType
     *
     * @param integer $usageType
     * @return Room
     */
    public function setUsageType($usageType) {
        if (array_key_exists($usageType, self::$usages)) {
            $this->usageType = $usageType;
        }

        return $this;
    }

    /**
     * Get usageType
     *
     * @return integer
     */
    public function getUsageType() {
        return $this->usageType;
    }

    /**
     * Set usageName
     *
     * @param string $usageName
     * @return Room
     */
    public function setUsageName($usageName) {
        $this->usageName = $usageName;

        return $this;
    }

    /**
     * Get usageName
     *
     * @return string
     */
    public function getUsageName() {
        return $this->usageName;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Room
     */
    public function setName($name) {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName() {
        return $this->name;
    }

    /**
     * Constructor
     */
    public function __construct() {
        $this->lessonTemplates = new \Doctrine\Common\Collections\ArrayCollection();
        $this->lessonsAssigned = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add lessonTemplates
     *
     * @param \Metaflo\SchemoBundle\Entity\LessonTemplate $lessonTemplates
     * @return Room
     */
    public function addLessonTemplate(\Metaflo\SchemoBundle\Entity\LessonTemplate $lessonTemplates) {
        $this->lessonTemplates[] = $lessonTemplates;

        return $this;
    }

    /**
     * Remove lessonTemplates
     *
     * @param \Metaflo\SchemoBundle\Entity\LessonTemplate $lessonTemplates
     */
    public function removeLessonTemplate(\Metaflo\SchemoBundle\Entity\LessonTemplate $lessonTemplates) {
        $this->lessonTemplates->removeElement($lessonTemplates);
    }

    /**
     * Get lessonTemplates
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getLessonTemplates() {
        return $this->lessonTemplates;
    }

    /**
     * Add lessonsAssigned
     *
     * @param \Metaflo\SchemoBundle\Entity\Lesson $lessonsAssigned
     * @return Room
     */
    public function addLessonsAssigned(\Metaflo\SchemoBundle\Entity\Lesson $lessonsAssigned) {
        $this->lessonsAssigned[] = $lessonsAssigned;

        return $this;
    }

    /**
     * Remove lessonsAssigned
     *
     * @param \Metaflo\SchemoBundle\Entity\Lesson $lessonsAssigned
     */
    public function removeLessonsAssigned(\Metaflo\SchemoBundle\Entity\Lesson $lessonsAssigned) {
        $this->lessonsAssigned->removeElement($lessonsAssigned);
    }

    /**
     * Get lessonsAssigned
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getLessonsAssigned() {
        return $this->lessonsAssigned;
    }

    /**
     * Set project
     *
     * @param \Metaflo\SchemoBundle\Entity\Project $project
     * @return Room
     */
    public function setProject(\Metaflo\SchemoBundle\Entity\Project $project = null) {
        $this->project = $project;

        return $this;
    }

    /**
     * Get project
     *
     * @return \Metaflo\SchemoBundle\Entity\Project
     */
    public function getProject() {
        return $this->project;
    }

    function __toString() {
        return $this->name;
    }

    public function getUsageTypeName() {
        return self::$usages[$this->usageType];
    }
}

src/Metaflo/SchemoBundle/Entity/Schedule.php
<?php

namespace Metaflo\SchemoBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Schedule
 *
 * @ORM\Table()
 * @ORM\Entity
 * @ORM\Entity(repositoryClass="Metaflo\SchemoBundle\Entity\ScheduleRepository")
 */
class Schedule {
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\Column(name="status", type="smallint")
     */
    private $status = 0;

    const STATUS_NOTDONE = 0;
    const STATUS_COMPLETED_ERRONOUS = 1;
    const STATUS_COMPLETED_GOOD = 2;
    public static $statuses = [
        self::STATUS_NOTDONE => "not done yet",
        self::STATUS_COMPLETED_ERRONOUS => "completed, with errors",
        self::STATUS_COMPLETED_GOOD => "completed"
    ];

    /**
     * @var integer
     *
     * @ORM\Column(name="collisions", type="integer")
     */
    private $collisions = 0;

    /**
     * @var float
     *
     * @ORM\Column(name="quality", type="float")
     */
    private $quality = 0;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="datetime", type="datetime", nullable=true)
     */
    private $datetime;

    /**
     * @var Project
     *
     * @ORM\OneToOne(targetEntity="Project", inversedBy="schedule")
     */
    private $project;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateStart;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateEnd;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set status
     *
     * @param integer $status
     * @return Schedule
     */
    public function setStatus($status) {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return integer
     */
    public function getStatus() {
        return $this->status;
    }

    /**
     * Set collisions
     *
     * @param integer $collisions
     * @return Schedule
     */
    public function setCollisions($collisions) {
        $this->collisions = $collisions;

        return $this;
    }

    /**
     * Get collisions
     *
     * @return integer
     */
    public function getCollisions() {
        return $this->collisions;
    }

    /**
     * Set quality
     *
     * @param float $quality
     * @return Schedule
     */
    public function setQuality($quality) {
        $this->quality = $quality;

        return $this;
    }

    /**
     * Get quality
     *
     * @return float
     */
    public function getQuality() {
        return $this->quality;
    }

    /**
     * Set datetime
     *
     * @param \DateTime $datetime
     * @return Schedule
     */
    public function setDatetime($datetime) {
        $this->datetime = $datetime;

        return $this;
    }

    /**
     * Get datetime
     *
     * @return \DateTime
     */
    public function getDatetime() {
        return $this->datetime;
    }

    /**
     * Set project
     *
     * @param \Metaflo\SchemoBundle\Entity\Project $project
     * @return Schedule
     */
    public function setProject(\Metaflo\SchemoBundle\Entity\Project $project = null)
    {
        $this->project = $project;

        return $this;
    }

    /**
     * Get project
     *
     * @return \Metaflo\SchemoBundle\Entity\Project 
     */
    public function getProject()
    {
        return $this->project;
    }

    public function getStatusName() {
        return self::$statuses[$this->status];
    }

    /**
     * Set dateStart
     *
     * @param \DateTime $dateStart
     * @return Schedule
     */
    public function setDateStart($dateStart)
    {
        $this->dateStart = $dateStart;

        return $this;
    }

    /**
     * Get dateStart
     *
     * @return \DateTime 
     */
    public function getDateStart()
    {
        return $this->dateStart;
    }

    /**
     * Set dateEnd
     *
     * @param \DateTime $dateEnd
     * @return Schedule
     */
    public function setDateEnd($dateEnd)
    {
        $this->dateEnd = $dateEnd;

        return $this;
    }

    /**
     * Get dateEnd
     *
     * @return \DateTime 
     */
    public function getDateEnd()
    {
        return $this->dateEnd;
    }
}

src/Metaflo/SchemoBundle/Entity/Timeslot.php
<?php

namespace Metaflo\SchemoBundle\Entity;

use Doctrine\Common\Proxy\Exception\InvalidArgumentException;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;
use JMS\Serializer\Annotation\MaxDepth;

/**
 * Timeslot
 *
 * @ORM\Table()
 * @ORM\Entity
 * @ExclusionPolicy("all")
 */
class Timeslot {
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\Column(type="smallint")
     * @Expose
     */
    private $weekday; //TODO: validate that each weekday-timeslot combination is unique
    const DAY_MON = 1;
    const DAY_TUE = 2;
    const DAY_WED = 3;
    const DAY_THU = 4;
    const DAY_FRI = 5;
    const DAY_SAT = 6;
    const DAY_SUN = 7;
    public static $DAYS = array(
        self::DAY_MON => "Mon",
        self::DAY_TUE => "Tue",
        self::DAY_WED => "Wed",
        self::DAY_THU => "Thu",
        self::DAY_FRI => "Fri",
        self::DAY_SAT => "Sat",
        self::DAY_SUN => "Sun",
    );

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="timeStart", type="time")
     * @Expose
     */
    private $timeStart;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="timeEnd", type="time")
     * @Expose
     */
    private $timeEnd;

    /**
     * @var Lesson[]
     *
     * @ORM\OneToMany(targetEntity="Lesson", mappedBy="timeslot")
     */
    private $lessons;

    /**
     * @var Project
     *
     * @ORM\ManyToOne(targetEntity="Project", inversedBy="timeslots")
     */
    private $project;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }


    /**
     * Set timeStart
     *
     * @param \DateTime $timeStart
     * @return Timeslot
     */
    public function setTimeStart($timeStart) {
        $this->timeStart = $timeStart;

        return $this;
    }

    /**
     * Get timeStart
     *
     * @return \DateTime
     */
    public function getTimeStart() {
        return $this->timeStart;
    }

    /**
     * Set timeEnd
     *
     * @param \DateTime $timeEnd
     * @return Timeslot
     */
    public function setTimeEnd($timeEnd) {
        $this->timeEnd = $timeEnd;

        return $this;
    }

    /**
     * Get timeEnd
     *
     * @return \DateTime
     */
    public function getTimeEnd() {
        return $this->timeEnd;
    }

    /**
     * Constructor
     */
    public function __construct() {
        $this->lessons = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add lessons
     *
     * @param \Metaflo\SchemoBundle\Entity\Lesson $lessons
     * @return Timeslot
     */
    public function addLesson(\Metaflo\SchemoBundle\Entity\Lesson $lessons) {
        $this->lessons[] = $lessons;

        return $this;
    }

    /**
     * Remove lessons
     *
     * @param \Metaflo\SchemoBundle\Entity\Lesson $lessons
     */
    public function removeLesson(\Metaflo\SchemoBundle\Entity\Lesson $lessons) {
        $this->lessons->removeElement($lessons);
    }

    /**
     * Get lessons
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getLessons() {
        return $this->lessons;
    }

    /**
     * Set project
     *
     * @param \Metaflo\SchemoBundle\Entity\Project $project
     * @return Timeslot
     */
    public function setProject(\Metaflo\SchemoBundle\Entity\Project $project = null) {
        $this->project = $project;

        return $this;
    }

    /**
     * Get project
     *
     * @return \Metaflo\SchemoBundle\Entity\Project
     */
    public function getProject() {
        return $this->project;
    }

    function __toString() {
        return $this->getWeekdayName() . " (" .
        $this->timeStart->format('H:i') . " - " .
        $this->timeEnd->format('H:i') . ")";
    }

    /**
     * Set weekday
     *
     * @param integer $weekday
     * @throws \Symfony\Component\DependencyInjection\Exception\InvalidArgumentException
     * @return Timeslot
     */
    public function setWeekday($weekday) {
        if (!array_key_exists($weekday, self::$DAYS))
            throw new \Symfony\Component\DependencyInjection\Exception\InvalidArgumentException(
                "weekday must be between 1 (Mon) and 7 (Sun)"
            );
        $this->weekday = $weekday;

        return $this;
    }

    /**
     * Get weekday
     *
     * @return integer
     */
    public function getWeekday() {
        return $this->weekday;
    }

    public function getWeekdayName() {
        return self::$DAYS[$this->weekday];
    }
}

src/Metaflo/SchemoBundle/Form/ProjectType.php
<?php

namespace Metaflo\SchemoBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ProjectType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Metaflo\SchemoBundle\Entity\Project'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'metaflo_schemobundle_project';
    }
}

src/Metaflo/SchemoBundle/Resources/views/Project/edit.html.twig
{% extends "MetafloSchemoBundle::layout.html.twig" %}

{% block title %}Project edit{% endblock %}

{% block content %}
    {{ form(edit_form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('project') }}">
            Back to the list
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}

src/Metaflo/SchemoBundle/Resources/views/Project/index.html.twig
{% extends "MetafloSchemoBundle::layout.html.twig" %}

{% block title %}Project list{% endblock %}

{% block content %}
    <table class="records_list">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for entity in entities %}
            <tr>
                <td><a href="{{ path('project_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
                <td>{{ entity.name }}</td>
                <td>
                    <ul>
                        <li>
                            <a href="{{ path('project_show', { 'id': entity.id }) }}">show</a>
                        </li>
                        <li>
                            <a href="{{ path('project_edit', { 'id': entity.id }) }}">edit</a>
                        </li>
                    </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <ul>
        <li>
            <a href="{{ path('project_new') }}">
                Create a new entry
            </a>
        </li>
    </ul>
{% endblock %}

src/Metaflo/SchemoBundle/Resources/views/Project/new.html.twig
{% extends "MetafloSchemoBundle::layout.html.twig" %}

{% block title %}Project creation{% endblock %}

{% block content %}
    {{ form(form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('project') }}">
            Back to the list
        </a>
    </li>
</ul>
{% endblock %}

src/Metaflo/SchemoBundle/Resources/views/Project/show.html.twig
{% extends "MetafloSchemoBundle::layout.html.twig" %}

{% block title %}Project{% endblock %}

{% block content %}
    <table class="record_properties">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ entity.id }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ entity.name }}</td>
        </tr>
        </tbody>
    </table>

    <ul class="record_actions">
        <li>
            <a href="{{ path('project') }}">
                Back to the list
            </a>
        </li>
        <li>
            <a href="{{ path('project_edit', { 'id': entity.id }) }}">
                Edit
            </a>
        </li>
        <li>{{ form(delete_form) }}</li>

    </ul>

    <div class="row">
        <div class="col-xs-12">
            <h3>
                Schedule
                <a href="{{ path('schedule', { 'id': entity.id }) }}" class="btn btn-primary">
                    view/edit/generate schedule
                </a>
            </h3>

            <p>status: {{ entity.schedule.statusName }}</p>
            {% if (entity.schedule.status > 1) %}
                <p>
                    date/time: {{ entity.schedule.datetime |date('Y-m-d - H:i:s') }}<br>
                    errors: {{ entity.schedule.errors }}
                    quality: {{ entity.schedule.quality }}
                </p>
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 panel panel-default">
            <h3>Lesson templates
                <a href="{{ path('lessontemplate_new') }}" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span> add
                </a>
            </h3>
            {% if entity.lessonTemplates is not empty %}
                <table class="records_list">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Class</th>
                        <th>Teachers</th>
                        <th>Room</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for lt in entity.lessonTemplates %}
                        <tr>
                            <td><a href="{{ path('lessontemplate_show', { 'id': lt.id }) }}">{{ lt.id }}</a></td>
                            <td>{{ lt.name }}</td>
                            <td>{{ lt.schoolgroup }}</td>
                            <td>{{ lt.teachers | join(", ") }}</td>
                            <td>{{ lt.roomTypical }}</td>
                            <td>
                                <a href="{{ path('lessontemplate_edit', { 'id': lt.id }) }}">edit</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No lesson templates found. Create some!</p>
            {% endif %}
        </div>
        <div class="col-md-6 panel panel-default">
            <h3>Teachers
                <a href="{{ path('teacher_new') }}" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span> add
                </a>
            </h3>
            {% if entity.teachers is not empty %}
                <table class="records_list">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for teacher in entity.teachers %}
                        <tr>
                            <td><a href="{{ path('teacher_show', { 'id': teacher.id }) }}">{{ teacher.id }}</a></td>
                            <td>{{ teacher.name }}</td>
                            <td>
                                <a href="{{ path('teacher_edit', { 'id': teacher.id }) }}">edit</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No teachers found. Create some!</p>
            {% endif %}
        </div>
        <div class="col-md-6 panel panel-default">
            <h3>Rooms
                <a href="{{ path('room_new') }}" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span> add
                </a>
            </h3>
            {% if entity.rooms is not empty %}
                <table class="records_list">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Usagetype</th>
                        <th>Usagename</th>
                        <th>Name</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for room in entity.rooms %}
                        <tr>
                            <td><a href="{{ path('room_show', { 'id': room.id }) }}">{{ room.id }}</a></td>
                            <td>{{ room.usageTypeName }}</td>
                            <td>{{ room.usageName }}</td>
                            <td>{{ room.name }}</td>
                            <td>
                                <a href="{{ path('room_edit', { 'id': room.id }) }}">edit</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No rooms found. Create some!</p>
            {% endif %}
        </div>
        <div class="col-md-6 panel panel-default">
            <h3>Timeslots
                <a href="{{ path('timeslot_new') }}" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span> add
                </a>
            </h3>
            {% if entity.timeslots is not empty %}
                <table class="records_list">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Weekday</th>
                        <th>Timestart</th>
                        <th>Timeend</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for timeslot in entity.timeslots %}
                        <tr>
                            <td><a href="{{ path('timeslot_show', { 'id': timeslot.id }) }}">{{ timeslot.id }}</a></td>
                            <td>{{ timeslot.weekdayName }}</td>
                            <td>{{ timeslot.timeStart|date('H:i:s') }}</td>
                            <td>{{ timeslot.timeEnd|date('H:i:s') }}</td>
                            <td>
                                <a href="{{ path('timeslot_edit', { 'id': timeslot.id }) }}">edit</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No timeslots found. Create some!</p>
            {% endif %}
        </div>
        <div class="col-md-6 panel panel-default">
            <h3>Schoolgroups
                <a href="{{ path('schoolgroup_new') }}" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span> add
                </a>
            </h3>
            {% if entity.schoolgroups is not empty %}
                <table class="records_list">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for sg in entity.schoolgroups %}
                        <tr>
                            <td><a href="{{ path('schoolgroup_show', { 'id': sg.id }) }}">{{ sg.id }}</a></td>
                            <td>{{ sg.name }}</td>
                            <td>
                                <a href="{{ path('schoolgroup_edit', { 'id': sg.id }) }}">edit</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No schoolgroups found. Create some!</p>
            {% endif %}
        </div>
    </div>
{% endblock %}